name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  XML file does not appear to have any style information associated with it. The document tree is shown below.
<feed xmlns="http://www.w3.org/2005/Atom">
<title type="text" xml:lang="en">Swift.org</title>
<link type="application/atom+xml" href="https://swift.org/atom.xml" rel="self"/>
<link type="text/html" href="" rel="alternate"/>
<updated>2022-03-02T22:05:14-04:00</updated>
<id>tag:swift.org,2015-12-03:Swift</id>
<entry>
<title>The Swift.org Blog</title>
<author>
<name>Swift.org</name>
</author>
<link href="https://swift.org/blog/welcome/"/>
<updated>2015-12-03T06:01:01-04:00</updated>
<id>https://swift.org/blog/welcome/</id>
<content type="html"><p>Welcome to the blog on Swift.org! Today we launched the open source Swift project along with the Swift.org website. We couldn’t be more excited to work together in an open community to find and fix issues, add enhancements, and bring Swift to new platforms.</p> <p>This blog is where the engineers working on Swift will make announcements and highlight important community topics.</p> <h2 id="projects">Projects</h2> <p>Swift is made up of a number of different projects, providing a complete ecosystem for building great software. The Swift compiler project interprets Swift syntax, produces diagnostics to help you write correct code, and employs LLVM to generate machine instructions. The LLDB project is a first-class debugger that includes a REPL for interactive programming. And the Swift standard library project includes all the core types and basic functionality you need to write software in Swift.</p> <p>Today, we released two additional projects for Swift in open source: the Core Libraries project, and a new Swift Package Manager project.</p> <h3 id="swift-package-manager">Swift Package Manager</h3> <p>The <a href="https://swift.org/package-manager/">Swift Package Manager</a> is a brand new project that strives to create a powerful, user-friendly tool to build and share Swift code. We are focused on ensuring the package manager is great at sharing source code, rather than compiled binary libraries. This project is very early in development, and will be designed and developed using Swift’s open, collaborative process.</p> <p>You can find example package repositories at <a href="http://github.com/apple">the Apple home on GitHub</a>, as well as the source code and additional information for the package manager itself.</p> <h3 id="core-libraries">Core Libraries</h3> <p>The <a href="https://swift.org/core-libraries/">Swift Core Libraries</a> project is a higher-level set of APIs, above the Swift standard library. These libraries offer functionality such as localization, networking primitives, unit testing, user preferences, and more. These libraries also introduce coding conventions that will be useful as you write more Swift code, and create new packages.</p> <p>The core libraries are based on frameworks included in Apple platforms, namely Foundation, libdispatch, and XCTest. The Swift open source versions of these frameworks are intended to make it easy to use the same Swift code with consistent functionality across multiple platforms.</p> <h2 id="swiftorg-website">Swift.org Website</h2> <p>This website is the home of the Swift project with links to the resources you will need to participate in the community. We invite you to click around the navigation area to explore the site, but we wanted to call out a few key links here in our inaugural post:</p> <ul> <li>The <a href="http://github.com/apple">Apple home on GitHub</a> hosts all the 
